CREATE TABLE USER(
	ID int(5) primary key auto_increment,
	NAME varchar(20) not null,
	GENDER CHAR(1),
	AGE INT,
	ADDRESS varchar(60),
	BIRTHDAY date ,
	CREATE_DATE  date,
	LST_UPD_TIME timestamp
) default charset=utf8;


CREATE TABLE USER_INFO(
	ID int(5) primary key auto_increment,
	NAME varchar(20) not null,
	GENDER CHAR(1),
	AGE INT,
	ADDRESS varchar(60),
	BIRTHDAY date ,
	CREATE_DATE  date,
	LST_UPD_TIME timestamp
) 

insert into USER_INFO(name, gender, age) values('张三', 'm', 20);


CREATE TABLE USER_MOBILE_RELATED(
	
	ID INT(5) PRIMARY KEY NOT NULL,
	USER_ID INT(5) NOT NULL,
	MOBILE VARCHAR(15) NOT NULL,
	CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	
);
CREATE INDEX mobile_index on USER_MOBILE_RELATED(mobile);


INSERT INTO USER_MOBILE_RELATED (USER_ID, MOBILE) VALUE(10001, '12155246731')
INSERT INTO USER_MOBILE_RELATED (USER_ID, MOBILE) VALUE(10002, '13755874456');
INSERT INTO USER_MOBILE_RELATED (USER_ID, MOBILE) VALUE(10003, '15488795564');


CREATE TABLE USER_INFO(

	USER_ID INT(5) PRIMARY KEY NOT NULL AUTO_INCREMET START BY 10001,
	USER_NAME VARCHAR(20) NOT NULL,
	MOBILE VARCHAR(15),
	SEX SMALLINT(5) NOT NULL COMMENT "0 女， 1 男",
	BIRTHDAY_DATE DATE,
	EMAIL VARCHAR(20),
	USER_STATUS SMALLINT(5) DEFAULT 0,
	CRT_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	LST_UPD_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	
);
INSERT INTO USER_INFO (USER_NAME, MOBILE, SEX ) VALUES ('测试', '12155246731',  1);
INSERT INTO USER_INFO (USER_NAME, MOBILE, SEX ) VALUES ('测试2', '13755874456',  0);
INSERT INTO USER_INFO (USER_NAME, MOBILE, SEX ) VALUES ('测试3', '15488795564',  1);















--修改列属性
ALTER TABLE USER_MOBILE_RELATED modify ID INT(5) auto_increment;
--设置auto_increment初始值
ALTER TABLE USER_MOBILE_RELATED AUTO_INCREMENT = 1;
--修改表名
alter table USER_MOBILE_RELATED rename user_mobile_related;

alter table USER_MOBILE_RELATED add primary key (ID);


